- name: Instaling nginx
  apt:
    name: nginx
    state: present

- name: Using template for localhost proxy
  template:
    src: nginx_template.j2
    dest: /etc/nginx/sites-available/default
    mode: 0744
