- name: downloading docker packages
  apt:
    name: docker.io
    state: present

- name: uploading docker compose template to server
  template:
    src: compose-django.yml.j2
    dest: /code/
    mode: 0744

